### ISSUE TITLE
Option to enable Milkdown by default

### ISSUE THREAD

**Issue by L1lith** [Saul-Mirone/milkdown-vscode#2]
It would be cool if there was an option we could configure to enable Milkdown for all .md files by default when they are opened (there might also need to be a way to say right click and open it raw or something)

**Comment by Saul-Mirone** [comment]
Sure, I'll make it in next version.

**Comment by Saul-Mirone** [comment]
https://github.com/microsoft/vscode/issues/115347

It seems that VSCode currently not support this feature, I'll follow this issue to see if there is any progress.

**Comment by Win7GM** [comment]
I think this can be solved by setting it manually and there's no much reason to add a option in the extension to do so.

1. Open an .md file
2. Right click tab of the file
3. Click "re-open..." or sth like this (I don't quite remember its exact words but it means to open the same file with **another editor** like hex editor or milkdown)
4. Then you can see the defualt editor option vscode offered, and you just have to click and change it.

Adding these instructions to the extension details will do the job. But users may still need to be prompted to read it tho.

**Comment by tieea** [comment]
> I think this can be solved by setting it manually and there's no much reason to add a option in the extension to do so.
> 
> 1. Open an .md file
> 2. Right click tab of the file
> 3. Click "re-open..." or sth like this (I don't quite remember its exact words but it means to open the same file with **another editor** like hex editor or milkdown)
> 4. Then you can see the defualt editor option vscode offered, and you just have to click and change it.
> 
> Adding these instructions to the extension details will do the job. But users may still need to be prompted to read it tho.

How can we set to open md files with milkdown by default? Nowadays, we need to select milkdown to open md files with 2 steps.

1. Open an md file, at this time there is native editor to open the md file.
2. Display all commands and input `>open with milkdown`.

However, it seems convenient to give a option to enable milkdown by default. I discovered that [cweijan/vscode-office](https://github.com/cweijan/vscode-office/) has the feature to enable its markdown editor by default instead of vscode native editor.

Thanks for your contribution.
